parameters = {
    "remove_cols": [
        "Accuracy (ppm)",
        "Retention Time (s)",
        "Complies search criteria",
        "Conflicting uparam",
        # "Spectrum Title",
        "Mass Difference",
        "Raw data location",
        "Rank",
        "Calc m/z",
    ],
    "proton": 1.00727646677,
    "remove_after_row_features": [
        "Sequence Post AA",
        "Sequence Pre AA",
        "Sequence Start",
        "Sequence Stop",
        "_score_min",
        "_score_max",
        "Score",
        "Exp m/z",
        "uCalc m/z",
    ],
    "training_features": {
        "Charge",
        "CountProt",
        "Mass",
        "PepLen",
        "Score_processed_mascot_1_0_0",
        "Score_processed_omssa_2_1_9",
        "Score_processed_xtandem_vengeance",
        "enzC",
        "enzInt",
        "enzN",
        "Score_processed_msgfplus_v2018_06_28",
        "delta_score_2_msgfplus_v2018_06_28",
        "delta_score_3_msgfplus_v2018_06_28",
        "Score_processed_msfragger_20190222",
        "delta_score_2_msfragger_20190222",
        "delta_score_3_msfragger_20190222",
        "mScore",
    },
    "hyperparameters": {"n_estimators": 100, "max_depth": 22, "max_features": 7},
}
