"""Knowledge database for peptide forest internal use."""
parameters = {
    "remove_cols": [
        "Rank",
        "Calc m/z",
        "Chemical Composition",
        "Spectrum Title",
    ],
    "proton": 1.00727646677,
    "remove_after_row_features": [
        "Sequence Post AA",
        "Sequence Pre AA",
        "Sequence Start",
        "Sequence Stop",
        "_score_min",
        "_score_max",
        "Score",
        "Exp m/z",
        "uCalc m/z",
    ],
    "non_trainable_columns": {
        "Raw data location",
        "Retention Time (s)",
        "Spectrum ID",
        "Sequence",
        "Modifications",
        "Is decoy",
        "Protein ID",
        "model_score",
        "model_score_all",
        "model_score_train",
        "model_score_train_all",
        "prev_score_train",
        "reported_by_",
    },
    "hyperparameters": {"n_estimators": 100, "max_depth": 22, "max_features": 7},
}
